/+
Org: http://nomad.so/2014/08/hidden-treasure-in-the-d-standard-library/

Here the random number generated by dice will be in the range defined by 0 and the maximum index of the passed weight i.e. it will be between 0 and 2 as there are only three weighted elements. The weights themselves (element values) act as percentages, causing the different indexes to be returned with more or less frequency than others. In this particular example, 0 will be returned seventy percent of the time, 1 twenty percent and 2 ten percent of the time.
+/
import std.random;
import std.stdio;
import std.string;
 
void main()
{
    auto weights = [70, 20, 10]; // z is 0 70% of the time, 1 20% of the time,
                           // and 2 10% of the time
	writeln("Pick 3 numbers");
	auto three = readln.chomp.split;
 
    foreach (x; 0 .. 100)
    {
        auto number = dice(weights);
 
        writefln("%s", three[number]);
    }
}
